### ISSUE TITLE
map.where('world', x, y) returning more than just country

### ISSUE THREAD

**Issue by RafaRafa** [adeckmyn/maps#10]
Why is this happening?

```
maps::map.where('world', -73.97058, 40.76813)
## "USA"
maps::map.where('world', -73.59143, 40.74178)
## "USA:New York:Long Island"
```
Why does the second call return more than just USA? 

link to: https://stackoverflow.com/questions/50875944/map-whereworld-x-y-returning-more-than-just-country

**Comment by adeckmyn** [comment]
Every polygon in the world map has a different name. 'USA' is the main, large mainland polygon of the USA. All other polygons of islands etc. that are also part of the US, have such longer names. The same scheme is used for all other countries as well. So you also will have 'France' and 'France:Corsica' etc.
When drawing a map, `maps::map('world','usa')` will in fact draw all polygons that start with these letters. But adding the option `exact=TRUE` will draw only the main polygon.

`map.where()` returns the full name of the polygon in which the point lies. If you only want the country name, you could use 

    strsplit( map.where(...), ':')[[1]][1]
