### ISSUE TITLE
Map Wrong name of islands in Puerto Rico

### ISSUE THREAD

**Issue by RaymondLTremblay** [adeckmyn/maps#14]
Hello.  The two mentioned islands associated with Puerto Rico are incorrectly identified/ spelled. 

The island you spelled as "Viaques" should be "Vieques"

Mona island should be "Isla de la Mona"

Note that on the Map of Puerto Rico you are missing the island of Culebra.

**Comment by adeckmyn** [comment]
Thanks. I'll fix the names. Adding a missing island is another matter, though. If NaturalEarth does not have it in the data set, it probably is too small at that resolution. I guess their high resolution map will have it.
Both google and wikipedia give me "Isla de Mona", not "Isla de la Mona".
