### ISSUE TITLE
Another wrong name in world.cities

### ISSUE THREAD

**Issue by taesimkim** [adeckmyn/maps#17]
Hello. I think "Seoul", the capital city of South Korea, is incorrectly listed as "Soul" in the world.cities dataset. Could we correct this error? 

> world.cities %>% 
+   filter(country.etc == "Korea South" & capital == 1)
  name country.etc      pop   lat   long capital
1 Soul Korea South 10409345 37.56 126.99       1

Thanks!

Taesim

**Comment by adeckmyn** [comment]
Indeed. Thanks for spotting this. It will be fixed in the next update to CRAN. The city table is becoming very out-dated as well, but that is a different matter.
