### ISSUE TITLE
`map.where`: Add better support for managing missing values

### ISSUE THREAD

**Issue by rempsyc** [adeckmyn/maps#24]
First, thank you for this very useful package.

I am working with large data sets and unavoidably, some will have missing values. It would be useful if the `map.where` function had an argument to output NA instead of throwing an error in the presence of missing values.

``` r
library(maps)
df <- data.frame(x = c(-82.0582, 82.0582), y = c(41, 41))
map.where(x = df$x, y = df$y)
#> [1] "USA"   "China"

df <- data.frame(x = c(-82.0582, 82.0582), y = c(41, NA))
map.where(x = df$x, y = df$y)
#> Error in map.where(x = df$x, y = df$y): NA/NaN/Inf in foreign function call (arg 3)

df <- data.frame(x = c(-82.0582, ""), y = c(41, 41))
map.where(x = df$x, y = df$y)
#> Error in map.where(x = df$x, y = df$y): NA/NaN/Inf in foreign function call (arg 2)

map.where(x = NA, y = 41)
#> Error in map.where(x = NA, y = 41): NA/NaN/Inf in foreign function call (arg 2)
map.where(x = "", y = 41)
#> Error in map.where(x = "", y = 41): NA/NaN/Inf in foreign function call (arg 2)
```
<sup>Created on 2022-10-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

In large data frames, that would make it more convenient to process it correctly if the information is available, and add an NA if not. Right now, it causes an error so it makes it more difficult to use. Is there already such an argument that I may have missed from the documentation?

**Comment by rempsyc** [comment]
So far, this is my workaround:

``` r
library(maps)
df <- data.frame(x = c(-82.0582, ""), y = c(41, 41))
for (i in seq(nrow(df))) {
  x <- df$x[i]
  y <- df$y[i]
  if (is.na(x) || is.na(y) || x == "" || y == "") {
    df$country[i] <- NA
  } else {
    df$country[i] <- maps::map.where(x = x, y = y)
  }
}
df
#>          x  y country
#> 1 -82.0582 41     USA
#> 2          41    <NA>
```

<sup>Created on 2022-10-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rempsyc** [comment]
Or as a function:

``` r
library(maps)
df <- data.frame(x = c(-82.0582, ""), y = c(41, 41))

map.where2 <- function(x, y, ...) {
  out <- NULL
  for (i in seq(length(x))) {
    a <- x[i]
    b <- y[i]
    if (is.na(a) || is.na(b) || a == "" || b == "") {
      out[i] <- NA
    } else {
      out[i] <- maps::map.where(x = a, y = b)
    }
  }
  out
}
map.where2(df$x, df$y)
#> [1] "USA" NA
```

<sup>Created on 2022-10-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by adeckmyn** [comment]
Thanks for the suggestion. I agree that a hard error is not really ideal. And there is no hidden option that you have missed. I think I can fix this in a pretty simple way by allowing NA values to be sent to the underlying C code and dealing with them there. That would be considerably easier (and faster) than your workaround.
The fix may appear in the github repository pretty soon, but it may take a bit longer to appear on CRAN. I only updated the package some hours before you opened this issue.

**Comment by adeckmyn** [comment]
Solved. NA entries will now return NA rather than an error.

**Comment by rempsyc** [comment]
Awesome, thanks so much!
